### ISSUE TITLE
Web Pages Outline

### ISSUE THREAD

**Issue by erykksc** [erykksc/kwikquiz#1]
## Objective:
The purpose of this issue is to plan and outline the essential web pages required for our quiz platform. This will include determining the purpose and basic features of each page to ensure a comprehensive user experience for both teachers (the ones creating and hosting quizzes) and students (the ones taking part in them).

## Required Pages:
I've come up with the following initial list of web pages. Give me your feedback which pages should be added, changed or deleted (this includes the features of each webpage).

Homepage
* Navigation to other pages such as Quiz Creation, Host Session, Join Session
* Overview of the platform features.

Browse Page
* Shows list of all public and private quizzes (created by the teacher)

Quiz Creation Page
* Page for creating a new quiz
* Should allow:
     * Naming the quiz
     * Adding questions and answers
     * Specifying the correct answer
* Options for settings, and quiz configurations like:
    * Time per question

Quiz Page
* Page for viewing an already existing Quiz
* Should allow to create a new quiz based on the original, if it doesn't belong to the user
* If the quiz belongs to the user, it should allow editing

Lobby Page
* A waiting area for students before the quiz starts.
* Displays session information, including quiz title and participant list.
* Allows the teacher to kick out unwanted participants (e.g. inappropriate username)
* Allows the teacher to start the session

Game Page
* Where the quiz takes place.
* Features real-time question display, answer submission, and timers.
* Shows whether the websocket connection to the server is active

Results Page
* Shows the quiz results after completion.
* Includes scores, correct answers, and rankings.
* Top 3 students featured prominently

## Discussion Points:
* What specific features should each page include?
* Which pages should be added, changed or deleted
* Which features of the pages should be added, changed or deleted
* How should navigation between pages be handled?

## Outcome:
By the end of this planning phase, we aim to have a clear blueprint for the front-end structure of our quiz platform, which will guide further development and design efforts.

## Next Steps:
* Sketch initial wireframes based on the outlined requirements
* Review and finalize the page outlines in follow-up issues

**Comment by ducminh02** [comment]
## Structure:

I think that in the first stage it is important that we come up with features for the app but also should prioritize on which features should be our focus and we can always add additional features later on in our project.

Here is my suggestion for adjusting the Pages Documentation

## Homepage :

- Goal:
    - Overview of the platform features
- Navigation to Leaderboard Page, Quiz List Page, Join Room Page, Create Quiz Page

## Quiz Creation Page:

- Goal:
    - Page for creating new quiz
- Design:
    - Each Slide for each question ( user can go back and forth between slides)
    - Overview of all the slides so it is easier for users to navigate between questions (optional)
- Slide:
    - Question
    - 4 Answers Format
    - Other format such as True/false, more answers, etc (optional)
- Configuration:
    - Time pro question
    - After the user done creating slides for the question and press save, here can the user set the Title and the Description of the Quiz

## Quiz Page:

- Goal:
    - Page for viewing an already existing Quiz
- Design:
    - Allow user create Quiz by navigating to Quiz Creation Page
    - Allow users to delete, edit existing Quiz
    - Only allow user to perform delete, edit existing quizzes if session key matches the creator of the Quiz. Meaning they belong to the user (optional)
    
    ## Lobby Page:
    
- Goal:
    - A waiting area for students before the quiz starts.
- Design:
    - Show random generated Room Code, 6 Digits for users to join
    - Show QR code (optional)
    - Displays room information, including quiz title and participant list.
    - Allows the teacher to start the session
    - Allows the teacher to kick out unwanted participants, e.g. inappropriate username (optional)
    - Waiting music (optional)

## Game Room Page:

- Goal:
    - Where the quiz takes place.
- Design:
    - Features real-time question display, answer submission, and timers.
    - Shows whether the websocket connection to the server is active
    - Show ranking on top of the screen
    - Show score after the answer is shown to all players
    - Show a crown icon if the person is currently leading (optional)

## Results page:

- Goal:
    - Shows the quiz results after completion.
- Design:
    - Includes scores, correct answers, and rankings.
    - Top 3 students featured prominently
    - Save the results to a database to have access to the results in the future

## Room Join Page

- Goal:
    - To join an existing room
- Design:
    - The user can join an existing Room with Room code, 6 Digits
    - Join via QR code (optional)

## Tech stack

- React (recommend)
- Vue js

## Navigation handling:

- For Frontend:
    - app name: frontend
    - Each Page would be a js component (React)
    - Each Page can be accessed with an url
- Urls (/frontend):
    - Homepage: ‘’
    - Room Join Page: ‘/join’
    - Create Quiz Page: ‘/create’
    - Results Page: ‘/results’
    - Game Room Page: ‘/room<str:roomCode>’
    - Lobby: ‘/lobby’
    - Quiz Page: ‘/quiz-pasges’

## Next steps:

- Your opinion on what should be added, changed, deleted on this draft
- Draw/ Design how each page should look like for the frontend
- Learn more about whichever framework we are using (frontend/ backend)

- Backend :
    - how does it handle the requests, api endpoints, generating random 6 digits codes for rooms (no duplicate) ?
    - how should it communicate with the frontend?
    - how can it save results to database?
    - how can it handle multiple game sessions?
    - how can we deploy it?
    - do we want to have the authentication, for example sign in with google? or just using session key to identify users is enough?
    - backend urls to handle requests?
