### ISSUE TITLE
New Design of Quiz Creation / Update Page

### ISSUE THREAD

**Issue by ducminh02** [erykksc/kwikquiz#46]
Can you guys push the new redesigned Quiz Creation Page when you guys are done, where:

- Answers of the Question can be dynamically added
- With a delete button for each Question (I have made an example delete button in the js file)
- Multiple questions can be marked as correct (Maybe the user can select it with checkbox?)
- Multiple formats of Questions / Answers (optional)

Update Page should be almost the same except for the instead of Create, the button shows Update and there it a big delete button to delete the whole quiz

After that I will make it work.

**Comment by Micmi15** [comment]
I will do this tonight, sorry I didnt find time yet!
